---
title: "Liga Mexicana Clusterizacion"
author: "Mahonry"
date: "22/4/2020"
output: html_document
knit: (function(inputFile, encoding) { 
      out_dir <- 'docs';
      rmarkdown::render(inputFile,
                        encoding=encoding, 
                        output_file=file.path(dirname(inputFile), out_dir, 'index.html')) })
---
```{r}
library(dplyr)

data <- read.csv("./data/clean_jugadores.csv")

data <- select(data, -X.1,-X,-Nombre,-Equipo...Posicion,-Nacionalidad )
write.csv(data, file = "./data/data.csv")

data <- scale(data)

mycluster<-kmeans(data, 3, nstart=5, iter.max = 30)

#Vemos el elbow para optimizar el numero de clusters
wss<-(nrow(data)-1)*sum(apply(data,2,var))

for(i in 2:20) wss[i]<-sum(kmeans(data,centers=i)$withinss)

wss

plot(1:20, wss, type="b", xlab="Numero de clusters", ylab= "withinss groups") 

# Creamos otra clusterizacion optimizando el numero de clusters ( = 7 )

mycluster<-kmeans(data, 7, nstart=5, iter.max = 30)

library(fmsb)
par(mfrow = c(2,4))

dat <- as.data.frame(t(mycluster$centers[1,]))
dat 
dat <- rbind(rep(.5,8),rep(-.3,8),dat)

radarchart(dat)

dat<-as.data.frame(t(mycluster$centers[2, ]))
dat
dat<-rbind(rep(5,10), rep(-1.5,10), dat)
dat
radarchart(dat)
dat<-as.data.frame(t(mycluster$centers[3, ]))
dat
dat<-rbind(rep(5,10), rep(-1.5,10), dat)
dat
radarchart(dat)
dat<-as.data.frame(t(mycluster$centers[4, ]))
dat
dat<-rbind(rep(5,10), rep(-1.5,10), dat)
dat
radarchart(dat)
dat<-as.data.frame(t(mycluster$centers[5, ]))
dat
dat<-rbind(rep(5,10), rep(-1.5,10), dat)
dat
radarchart(dat)
dat<-as.data.frame(t(mycluster$centers[6, ]))
dat
dat<-rbind(rep(5,10), rep(-1.5,10), dat)
dat
radarchart(dat)
dat<-as.data.frame(t(mycluster$centers[7, ]))
dat
dat<-rbind(rep(5,10), rep(-1.5,10), dat)
dat
radarchart(dat)

```
```{r}
function(input, output, session) {
  data <- read.csv("./data/data.csv")
  data <- data[,-1]

  selectedData <- reactive({
    data[, c(input$xcol, input$ycol)]
  })
  
  clusters <- reactive({
    kmeans(selectedData(), input$clusters)
  })
  
  output$plot1 <- renderPlot({
    palette(c("#E41A1C", "#377EB8", "#4DAF4A", "#984EA3",
              "#FF7F00", "#FFFF33", "#A65628", "#F781BF", "#999999"))
    
    par(mar = c(5.1, 4.1, 0, 1))
    plot(selectedData(),
         col = clusters()$cluster,
         pch = 20, cex = 3)
    points(clusters()$centers, pch = 4, cex = 4, lwd = 4)
  })
  
}
```




